name: Build and deploy
on:
  push:
    branches: [uat]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-file
          path: src/
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: html-file
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: orio.tech
          username: bienvenue-admin@orio.tech
          password: ${{ secrets.ftppassword }}
